export default [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
  "Western",
];
export const GenresColor = {
  Action: "blue",
  Adventure: "green",
  Animation: "teal",
  Comedy: "yellow",
  Crime: "orange",
  Documentary: "purple",
  Drama: "pink",
  Fantasy: "cyan",
  Horror: "red",
  Musical: "yellow",
  Mystery: "blue",
  Romance: "pink",
  "Sci-Fi": "blue",
  Thriller: "green",
  War: "orange",
  Western: "indigo",
};
